### ISSUE TITLE
Unable to build vignette when install?

### ISSUE THREAD

**Issue by dikiprawisuda** [EvaYiwenWang/PLSDAbatch_workflow#2]
Dear developer(s), thank you for the package.
I found an error when installing when turning `build_vignettes = TRUE`. With it being FALSE however, there's no problem.

Please find the error message as the following (after installing mixOmics):
`Downloading GitHub repo EvaYiwenWang/PLSDAbatch@HEAD
Skipping 1 packages not available: mixOmics
√  checking for file 'C:\Users\dikip\AppData\Local\Temp\RtmpuGhFHh\remotesbe82bc482d\EvaYiwenWang-PLSDAbatch-45c4798/DESCRIPTION' ...
-  preparing 'PLSDAbatch': (873ms)
√  checking DESCRIPTION meta-information ... 
-  installing the package to process help pages
   Loading required namespace: PLSDAbatch
   Registered S3 methods overwritten by 'lme4':
     method                          from
     cooks.distance.influence.merMod car 
     influence.merMod                car 
     dfbeta.influence.merMod         car 
     dfbetas.influence.merMod        car 
-  saving partial Rd database (533ms)
E  creating vignettes (4s)
   --- re-building 'case_studies.Rmd' using rmarkdown
   Registered S3 methods overwritten by 'lme4':
     method                          from
     cooks.distance.influence.merMod car 
     influence.merMod                car 
     dfbeta.influence.merMod         car 
     dfbetas.influence.merMod        car 
   Loading required package: MASS
   Loading required package: lattice
   Loading required package: ggplot2
   
   Loaded mixOmics 6.14.0
   Thank you for using mixOmics!
   Tutorials: http://mixomics.org
   Bookdown vignette: https://mixomicsteam.github.io/Bookdown
   Questions, issues: Follow the prompts at http://mixomics.org/contact-us
   Cite us:  citation('mixOmics')
   
   Quitting from lines 41-48 (case_studies.Rmd) 
   Error: processing vignette 'case_studies.Rmd' failed with diagnostics:
   there is no package called 'sva'
   --- failed re-building 'case_studies.Rmd'
   
   --- re-building 'simulation_study.Rmd' using rmarkdown
   Quitting from lines 60-65 (simulation_study.Rmd) 
   Error: processing vignette 'simulation_study.Rmd' failed with diagnostics:
   there is no package called 'sva'
   --- failed re-building 'simulation_study.Rmd'
   
   SUMMARY: processing the following files failed:
     'case_studies.Rmd' 'simulation_study.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'PLSDAbatch' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Quitting from lines 60-65 (simulation_study.Rmd) 
E> Error: processing vignette 'simulation_study.Rmd' failed with diagnostics:
E> there is no package called 'sva'
E> --- failed re-building 'simulation_study.Rmd'
E> 
E> SUMMARY: processing the following files failed:
E>   'case_studies.Rmd' 'simulation_study.Rmd'
E> 
E> Error: Vignette re-building failed.
E> Execution halted`

Thank you.

**Comment by EvaYiwenWang** [comment]
Hi dikiprawisuda, thanks for using our package. I think the reason why you cannot build the vignette is that you lack the packages required for the vignette. Could you try 'devtools::install_github("https://github.com/EvaYiwenWang/PLSDAbatch", dependencies = T, build_vignettes = T)'? Let me know if the problem is solved.

**Comment by dikiprawisuda** [comment]
Hi, yes it worked for me. Thank you!
