### ISSUE TITLE
Will it work if batches are sample's variable (longitudinal)?

### ISSUE THREAD

**Issue by dikiprawisuda** [EvaYiwenWang/PLSDAbatch_workflow#3]
Dear developer,

Thank you for the package. I hope it is okay to ask this here. If batches are variable, will it be okay to use this package (i.e. not affecting the data)? For example, my samples are consist of three sequencing batches, but they happen to be associated(?) with sample's age (longitudinal study). Do the statistics still hold up in these cases? Or should other settings be used?

You might have addressed this in the paper and I might have just missed it.

Thank you.
Best,

**Comment by EvaYiwenWang** [comment]
Hello dikiprawisuda,

Could I have a look at your design of sequencing batches x age? I am not very sure about your association between these two variables. Another question is what is your effect of interest? Age? 

Regards,
Eva

**Comment by dikiprawisuda** [comment]
Thank you for your response.

Sure, can I send it through email? Basically, we have two groups of treatment and control which are sequenced repeatedly (for now three times), so now we have three sequencing data. In addition, within the big groups (treatment and control) there are two subgroups of age subject, so one sequencing run contain two age groups not one.

Yes, we are interested in the treatmentxcontrol and sample's age microbiome differences.

**Comment by EvaYiwenWang** [comment]
Hello there,

[IMG_5882.HEIC.pdf](https://github.com/EvaYiwenWang/PLSDAbatch/files/5872248/IMG_5882.HEIC.pdf)

I hope my drawing is not that bad. :) From my understanding, your design (seq batch x treatment) is balanced, you can definitely use our package to remove the seq batch effects. You can use PCA to visualise your batch variation first. If the variation is large enough to be detected, then I recommend using sPLSDA-batch, if not, but you still want to remove it, I recommend using PLSDA-batch. However, the choice of method highly depends on the data, so always check before and after batch correction to ensure the preservation of your treatment variation. 

Good luck,
Eva
Email: yiwenw5@student.unimelb.edu.au
