### ISSUE TITLE
Scatter_density plot - set color

### ISSUE THREAD

**Issue by miguensblanco** [EvaYiwenWang/PLSDAbatch_workflow#4]
Hi! 

Thanks for the amazing package 

I have been able to set the colors for the other graphs but there is no chance that I get around it for the Scatter_density plot.
Any help would be really appreciate, I have been trying for a while :)

Thanks,

Jesus

**Comment by EvaYiwenWang** [comment]
Hey Jesus!

Sorry for the late reply.

I did not offer the options for color change in Scatter_density plot. I will update a new version. Many thanks for your good suggestion.

Best,

Eva

**Comment by EvaYiwenWang** [comment]
The package has been updated and the issue has been solved.
